<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="Analogy.CommonUtilities" Version="9.0.6" />
		<PackageVersion Include="Analogy.LogViewer.Interfaces" Version="9.0.6" />
		<PackageVersion Include="Analogy.LogViewer.Template" Version="9.0.6" />
		<PackageVersion Include="Analogy.LogViewer.Template.WinForms" Version="9.0.6" />
		<PackageVersion Include="Meziantou.Analyzer" Version="3.0.296" />
		<PackageVersion Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="5.9.0" />
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
		<PackageVersion Include="Roslynator.Analyzers" Version="5.0.1" />
		<PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
		<PackageVersion Include="System.Resources.Extensions" Version="10.0.12" />
	</ItemGroup>
</Project>
